const ROUTES = {
  ROOT: "/",
  ABOUT: "/about",
  CARDS: "/cards",
  SINGUP: "/singup",
  MY_CARDS: "/my-cards",
  FAV_CARDS: "/fav-cards",
  CARD_DETATLS: "/card-info",

  SANDBOX: "/sandbox",
  LOGIN: "/login",
};
export const SANDBOX_ROUTES_FATHER = {
  COMPONENT: "component",
  EVENTS: "events",
  INTRODUCTION: "introduction",
  MUI_SANDBOX: "mui_sandbox",
  NAVIGATION: "navigation",
  PROPS: "props",
  USE_STATE: "use_state",
  LIFESYCLE: "lifesecily-hooks",
  CUSTOM: "custom",
  MEMOIZAITON: "memoizition",
  CONTEXT: "context",
  FORM_TEST: "form",
};
export const SANDBOX_ROUTES_SONS = {
  TEMPLATE: "template",
  LOGIC: "logic",
  STYLES: "styles",
  EVENT_ONCLICK: "onClick",
  EVENT_RAISING_EVENT: "raising_event",
  INTRODUCTION_BABLE: "bable",
  MUI_SANDBOX_MUI_TYPOGRAPHY: "mui_typography",
  NAVIGATION_MUI_APP_BAR: "mui_appBar",
  NAVIGATION_MUI_BOTTOM_NAVIGATION: "mui_botton_navigation",
  USE_STATE_SEET_POST: "set_post",
  USE_STATE_SET_POSTS: "set_posts",
  USE_STATE_USE_STATE: "use_State",
  USE_STATE_ARRAY_OF_OBJ: "array_ofObbj",
  USE_STATE_COMPLEX_OBJ: "complexObj",
  USE_STATE_WITH_FUNCTION: "function",
  USE_STATE_WITH_OBJ: "objects",
  LIFESYCLE_INITIAL: "initial",
  LIFESYCLE_USE_STATE: "use-state-life",
  LIFESYCLE_LIFE_CYCLE: "life-cycle",
  LIFESYCLE_MOUNT: "mount",
  LIFESYCLE_UPDATE: "update",
  LIFESYCLE_UN_MOUNT: "unMount",
  LIFESYCLE_NO_DEPENDENCIES: "no-dependencies",
  CUSTOM_COUNTER: "counter",
  CUSTOM_NAME: "name",
  USE_MEMO: "memo",
  USE_CALLBACK: "call-back",
  CONTEXT_NAME: "con-name",
  CONTEXT_SNACK: "con-snack",
};

export default ROUTES;
